### ISSUE TITLE
Confused

### ISSUE THREAD

**Issue by Satan-the-Dragoon** [ClothCreators/PluginArrayLists#1]
What exactly does everything do? What is its purpose? Im not exactly sure what it all does from looking at it. How is the index structured? Is it one big array or is it a bunch of smaller ones? It may be obvious, but I am clearly missing it. lolz

Thanks in advance

**Comment by Goldorion** [comment]
It adds the ArrayList class, so if you don't know what it is or how to use, search on the Internet or don't use it. It's not the place to ask something like that.
